name: Publish

on:
  release:
    types: [published]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish Linux binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/tictactoe
          asset_name: tictactoe-linux
      - name: Build without Unicode
        run: cargo build --release --no-default-features --verbose
      - name: Upload binary (no Unicode)
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/tictactoe
          asset_name: tictactoe-ascii-linux

  build-windows:
    name: Publish Windows binaries
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/tictactoe.exe
          asset_name: tictactoe-win64.exe
      - name: Build without Unicode
        run: cargo build --release --no-default-features --verbose
      - name: Upload binary (no Unicode)
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/tictactoe.exe
          asset_name: tictactoe-ascii-win64.exe
