name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: rustfmt
        run: cargo fmt --check
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose
      - name: Clippy (ASCII)
        run: cargo clippy --no-default-features --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests (ASCII)
        run: cargo test --no-default-features --verbose
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
